export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_CLEAR = 'ALERT_CLEAR';

export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const PRODUCTS_FETCH_REQUEST = 'PRODUCT_FETCH_REQUEST';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCTS_FETCH_FAILURE = 'PRODUCT_FETCH_FAILURE';

export const REGISTER = "REGISTER";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const INCREASE_CART_ITEM = "INCREASE_CART_ITEM";
export const DECREASE_CART_ITEM = "DECREASE_CART_ITEM";
